export function getTldrawAgentCapabilities() {
    return {
        version: 1,
        enabled: true,
        agentPrompt: [
            'You operate an STtools-enhanced tldraw whiteboard inside SiYuan. Prefer tldraw_apply_plan for most whiteboard edits; it automatically uses the focused whiteboard when whiteboardId is omitted and supports $selection/$created/$last references.',
            'Keep tool results compact. Compact results intentionally omit raw selected shape IDs and shape samples. Use resultMode:"full", tldraw_get_interaction_context includeSelectedShapeIds:true, tldraw_get_summary includeShapeSamples:true, or tldraw_get_shape_details only when debugging or when exact IDs/bounds/details are necessary.',
            'Use low-level tldraw actions only when tldraw_apply_plan cannot express the requested edit or you need precise one-off control.',
            'Default shape preference: use card, single-block, text, bezier-connector, frame, and branch first. Use branch for mind maps, tree/parent-child/hierarchical layouts, or explicitly branch-connected components. Unless the user explicitly asks for another shape type or the task clearly requires it, avoid note, geo, arrow, line, draw, highlight, slide, mind-map, and js-shape.',
            'Prefer semantic STtools shapes over generic drawings: card for a document/heading block or substantial content, single-block for one paragraph block or compact atomic item, text for unlinked labels/annotations, branch for hierarchical/mind-map structures, bezier-connector for ordinary labeled relationships, and frame for grouping or visual boundaries.',
            'When creating multiple entity shapes, rely on tldraw_apply_plan aliases such as $created.name, $last, and $selection instead of repeating raw shape IDs. Use tldraw_get_shape_details bounds only when exact spatial planning is needed.',
            'Use tldraw_get_shape_details with includeBindings:true before editing unfamiliar shapes. Use update_shape isCollapsed:false/true to expand/collapse card shapes. Use batch_update for moving/resizing many shapes. Use create_connector instead of a plain line when two shapes should remain connected.',
        ],
        preferred: [
            'tldraw_apply_plan',
        ],
        read: [
            'tldraw_get_interaction_context',
            'tldraw_list_whiteboards',
            'tldraw_get_summary',
            'tldraw_get_shape_details',
            'tldraw_get_snapshot_summary',
            'tldraw_list_backups',
            'tldraw_preview_backup',
            'siyuan_read_doc_outline_for_tldraw',
        ],
        openNavigateSave: [
            'tldraw_open_whiteboard',
            'tldraw_select_shape',
            'tldraw_zoom_to_shapes',
            'tldraw_navigate_to_block',
            'tldraw_save_whiteboard',
        ],
        createEditLayout: [
            'tldraw_apply_plan',
            'tldraw_create_shape',
            'tldraw_create_basic_shape',
            'tldraw_create_connector',
            'tldraw_update_shape',
            'tldraw_batch_update_shapes',
            'tldraw_duplicate_shapes',
            'tldraw_arrange_shapes',
            'tldraw_align_shapes',
            'tldraw_group_shapes',
            'tldraw_lock_shapes',
            'tldraw_convert_connectors',
            'tldraw_insert_doc_outline_mindmap',
            'siyuan_create_summary_doc_whiteboard',
        ],
        toolSelectionHints: {
            preferredPlan: {
                action: 'tldraw_apply_plan',
                purpose: 'Default entrypoint for creating, branch-connecting hierarchical content, connecting relationship lines, updating, laying out, focusing, and saving through a safe JSON plan.',
                references: ['$selection', '$selection[0]', '$created.name', '$created.name[0]', '$last'],
                resultMode: 'compact by default; use full only for debugging',
                exampleArgs: {
                    goal: 'Create a branch from the current selection',
                    steps: [
                        { op: 'branch', root: '$selection[0]', child: '$selection[1]' },
                        { op: 'focus', target: '$last' },
                    ],
                    save: true,
                    zoom: true,
                },
            },
            createBusinessShapes: {
                action: 'tldraw_create_shape',
                kinds: ['card', 'single-block', 'branch'],
                defaultKinds: ['card', 'single-block', 'branch'],
                nonDefaultKinds: [],
                guidance: 'Use card and single-block for content nodes. Use branch for mind maps, tree/parent-child/hierarchical layouts, or explicitly branch-connected components; prefer tldraw_apply_plan op "branch" when possible.',
                exampleArgs: { whiteboardId: '<focusedWhiteboardId>', kind: 'single-block', contentMarkdown: 'New compact note', zoom: false },
            },
            createBasicShapes: {
                action: 'tldraw_create_basic_shape',
                kinds: ['text', 'note', 'geo', 'arrow', 'line', 'draw', 'highlight', 'frame', 'bezier-connector', 'slide', 'mind-map', 'js-shape'],
                defaultKinds: ['text', 'frame', 'bezier-connector'],
                nonDefaultKinds: ['note', 'geo', 'arrow', 'line', 'draw', 'highlight', 'slide', 'mind-map', 'js-shape'],
                guidance: 'Use text, frame, and bezier-connector by default for unlinked annotations, grouping, and ordinary relationships. For mind maps and hierarchical structures, prefer branch via tldraw_apply_plan. Use editable mind-map only when explicitly requested.',
                exampleArgs: { whiteboardId: '<focusedWhiteboardId>', kind: 'text', x: 100, y: 100, text: 'test', zoom: false },
            },
            createConnectorsBetweenShapes: {
                action: 'tldraw_create_connector',
                exampleArgs: { whiteboardId: '<focusedWhiteboardId>', shapeIds: ['shape:<source>', 'shape:<target>'], text: 'label', zoom: false },
            },
        },
        customShapeGuide: [
            {
                type: 'card',
                purpose: 'A large SiYuan document or heading card. Use it for article sections, overview documents, or cards that should show rich SiYuan content.',
                createWith: 'tldraw_create_shape',
                agentExposedArgs: {
                    kind: 'card',
                    x: 'page x coordinate',
                    y: 'page y coordinate',
                    w: 'width, default 300',
                    h: 'height, default 300',
                    color: 'tldraw color name or hex-like value normalized to nearest tldraw color',
                    blockId: 'optional SiYuan document or heading block id for referencing existing content',
                    contentMarkdown: 'optional Markdown for creating new card content; if it starts with a heading, the heading is used/deduplicated as the bound card heading; mutually exclusive with blockId',
                    title: 'optional title for a newly-created card heading; if omitted, the manual card title template/timestamp is used',
                    isMain: 'true for a main document card with stronger title/header presentation',
                    isCollapsed: 'true to show a compact summary/title state instead of full content',
                    showMask: 'visual mask flag, default true',
                    select: 'select after create unless false',
                    zoom: 'zoom to result unless false',
                },
                nativePropsAndBehavior: [
                    'Native props include w,h,color,showMask,blockId,isNewlyCreated,fontSize,isMain,refreshNonce,isCollapsed,preCollapseHeight,collapsedTextSize,collapsedTextAlign,renderMode.',
                    'Can resize, rotate, edit, scroll, export to SVG, and show connector ports.',
                    'Agent card creation is simple: use blockId to reference existing content, or contentMarkdown/title to create a new heading block and insert body content after it.',
                    'Content comes from the bound SiYuan block; do not pass text to update a card. To change content, edit the SiYuan block, not the shape props.',
                    'renderMode may be inherit/static-dom/live-protyle internally, but Agent should not raw-mutate it.',
                ],
                operations: [
                    'Create a linked card from an existing blockId, or create new content with contentMarkdown/title.',
                    'Move/resize/recolor and expand/collapse with tldraw_update_shape or batch_update using isCollapsed:false/true.',
                    'Connect to other shapes with tldraw_create_connector.',
                    'Use as branch root or branch child; child objects can set card-specific isMain/isCollapsed/showMask.',
                ],
            },
            {
                type: 'single-block',
                purpose: 'A compact SiYuan paragraph block. Use it for atomic notes, branch leaves, labels, todos, and short facts.',
                createWith: 'tldraw_create_shape',
                agentExposedArgs: {
                    kind: 'single-block',
                    x: 'page x coordinate',
                    y: 'page y coordinate',
                    w: 'width, default 300',
                    h: 'initial/minimum height, default 50; actual rendered height may grow with content',
                    color: 'tldraw color',
                    blockId: 'optional SiYuan paragraph block id; must be a paragraph when supplied',
                    contentMarkdown: 'optional Markdown/text for creating a new paragraph block; mutually exclusive with blockId',
                    title: 'optional fallback text for a newly-created paragraph when contentMarkdown is omitted',
                    select: 'select after create unless false',
                    zoom: 'zoom to result unless false',
                },
                nativePropsAndBehavior: [
                    'Native props include w,h,color,blockId,isNewlyCreated,fontSize,refreshNonce,connectOnEnter,transparentBackground,allowBinding.',
                    'Can resize, rotate, edit, scroll, auto-measure height, show database attribute bar, show connector ports unless transparent, and bind/anchor to other shapes when allowBinding is true.',
                    'Agent single-block creation is simple: use blockId to reference an existing paragraph block, or contentMarkdown/title to create a new paragraph block.',
                    'Content comes from the bound SiYuan paragraph; Agent update_shape cannot change the text.',
                ],
                operations: [
                    'Create a linked single-block from an existing blockId, or create new paragraph content with contentMarkdown/title.',
                    'Move/resize/recolor with update tools.',
                    'Use as branch child or connector endpoint.',
                    'Avoid deletion unless the user explicitly accepts linked-block deletion risk.',
                ],
            },
            {
                type: 'branch',
                purpose: 'A visual branch layout that attaches a root shape to left/right child shapes. Use it for mind maps, tree/parent-child/hierarchical layouts, and explicitly branch-connected components.',
                createWith: 'tldraw_apply_plan op "branch" preferred; tldraw_create_shape for low-level compatibility',
                agentExposedArgs: {
                    kind: 'branch',
                    x: 'root point x; if rootShapeId is set and x/y omitted, root point defaults to root shape center',
                    y: 'root point y',
                    rootShapeId: 'optional existing card/single-block/shape id used as branch root content',
                    childIds: 'existing child shape ids placed on direction side',
                    children: 'mixed child refs; string shape id or object {shapeId} or {kind:"card"|"single-block", blockId,w,h,color,side}',
                    leftChildren: 'child refs forced to left side',
                    rightChildren: 'child refs forced to right side',
                    direction: '"right" or "left"; default right; generic children and childIds use this side',
                    horizontalGap: 'distance from root to children, clamped 20..2000, default 96',
                    verticalGap: 'vertical spacing, clamped 8..1000, default 28',
                    lineStyle: '"curve-solid"|"elbow-solid"|"straight-solid"|"curve-dashed"|"frame-floating"',
                    lineWidth: 'stroke width, clamped 1..24, default 3',
                    snapDistance: 'drag attach/detach snap distance, clamped 40..2000, default 160',
                    showBackground: 'true adds a light background area',
                    color: 'branch stroke/background color',
                    select: 'select after create unless false',
                    zoom: 'zoom to result unless false',
                },
                nativePropsAndBehavior: [
                    'Native props include w,h,color,childIds,leftChildIds,rightChildIds,rootShapeId,rootX,direction,horizontalGap,verticalGap,lineWidth,lineStyle,snapDistance,showBackground,version.',
                    'Branch is not manually resized or edited as text; layout is driven by root/children and gaps.',
                    'Moving a branch moves attached child shapes. Dragging cards/single-blocks can attach/detach and relayout.',
                    'frame-floating draws a floating frame instead of per-child connector lines.',
                ],
                operations: [
                    'Create a branch from existing shapes with tldraw_apply_plan: {op:"branch",root:"$selection[0]",child:"$selection[1]"}.',
                    'Create child cards/single-blocks inside the branch in one call.',
                    'Use leftChildren/rightChildren for bilateral maps.',
                    'Use lineStyle/showBackground/color to adjust visual grouping.',
                ],
            },
            {
                type: 'bezier-connector',
                purpose: 'A curved, bindable relationship connector with optional label. Use it for semantic links between shapes.',
                createWith: 'tldraw_create_connector preferred; tldraw_create_basic_shape only for an unbound standalone curve',
                agentExposedArgs: {
                    kind: '"bezier-connector" default in create_connector',
                    shapeIds: '[sourceId,targetId], preferred; ports are chosen automatically',
                    startShapeId: 'source shape id alternative',
                    endShapeId: 'target shape id alternative',
                    start: 'fallback page point {x,y} for unbound start',
                    end: 'fallback page point {x,y} for unbound end',
                    color: 'connector color',
                    text: 'optional label text',
                    strokeWidth: 'line width, clamped 1..16 in create_connector',
                    select: 'select after create unless false',
                    zoom: 'zoom to result unless false',
                },
                nativePropsAndBehavior: [
                    'Native props include start,end,color,strokeWidth,strokeStyle,richText,labelPosition,font,size,scale.',
                    'strokeStyle can be solid/dashed/flowing internally. Agent currently creates solid connectors.',
                    'Can edit label rich text, drag label along curve, drag endpoints, and bind endpoints to visible shape ports.',
                    'Connectors are sent behind content after creation.',
                ],
                operations: [
                    'Connect two existing shapes with automatic ports.',
                    'Create labeled relationships.',
                    'Convert between bezier-connector and tldraw arrow with tldraw_convert_connectors.',
                    'Update label text with batch_update text patch; update_shape only changes geometry/color/size.',
                ],
            },
            {
                type: 'mind-map',
                purpose: 'An editable mind map shape. This is not a default shape; use branch for ordinary agent-created mind maps and use this only when the user explicitly requests the editable mind-map shape or when importing markdown-derived outlines through dedicated outline tools.',
                createWith: 'tldraw_create_basic_shape',
                agentExposedArgs: {
                    kind: 'mind-map',
                    x: 'page x coordinate',
                    y: 'page y coordinate',
                    w: 'initial width, default 800; actual geometry is measured from layout',
                    h: 'initial height, default 500',
                    color: 'base color',
                    text: 'root node text',
                    direction: '"right"|"left"|"both"; agent parser accepts these; component layout currently uses directional layout',
                    theme: 'theme string such as default/colorful/minimal',
                    blockId: 'optional SiYuan block id; when supplied, it renders markdown from the block and disables manual node editing',
                    select: 'select after create unless false',
                    zoom: 'zoom to result unless false',
                },
                nativePropsAndBehavior: [
                    'Native props include w,h,color,rootNode,horizontalGap,verticalGap,nodeWidth,nodeHeight,fontSize,lineWidth,direction,theme,selectedNodeId,version,blockId,refreshNonce.',
                    'Editable mode supports selecting nodes, double-click editing text, adding child/sibling nodes, deleting, dragging/reparenting, folding, node color, paste/replace markdown, and markdown export.',
                    'Linked block mode reads markdown from SiYuan and is read-only on canvas.',
                    'Agent can only create a root-text mind-map or insert doc outlines via dedicated tools; arbitrary rootNode mutation is intentionally blocked.',
                ],
                operations: [
                    'Create a blank/simple mind map with root text.',
                    'Use tldraw_insert_doc_outline_mindmap for document outlines.',
                    'Use batch_update text patch to rename the root node only.',
                    'Connect external shapes to mind-map node ports with bezier connectors when ports are available.',
                ],
            },
            {
                type: 'slide',
                purpose: 'A rectangular slide/frame area for presentation focus and screenshot export. This is not a default shape; prefer frame for ordinary grouping and use slide only when the user asks for presentation pages, slide focus, or screenshot/export workflow.',
                createWith: 'tldraw_create_basic_shape',
                agentExposedArgs: {
                    kind: 'slide',
                    x: 'page x coordinate',
                    y: 'page y coordinate',
                    w: 'width, default 720',
                    h: 'height, default 480',
                    color: 'border/fill accent color',
                    name: 'slide name shown above the frame',
                    text: 'fallback name when name is omitted',
                    blockId: 'optional SiYuan block id associated with a saved screenshot',
                    select: 'select after create unless false',
                    zoom: 'zoom to result unless false',
                },
                nativePropsAndBehavior: [
                    'Native props include w,h,name,version,color,screenshot,blockId,borderStyle.',
                    'borderStyle is solid/dashed/wavy internally; Agent currently creates dashed and can rename with name patch.',
                    'Can resize, edit name, double-click edge to focus, copy link, capture/update screenshot, and open associated SiYuan block through UI.',
                    'Slides do not bind connector endpoints.',
                ],
                operations: [
                    'Create slide frames around planned content.',
                    'Rename with batch_update name patch.',
                    'Move/resize/recolor with update tools.',
                    'Use zoom/select to present a specific slide.',
                ],
            },
            {
                type: 'js-shape',
                purpose: 'A sandboxed custom JavaScript-rendered panel. Agent may create only a restricted placeholder; do not generate or inject arbitrary script content.',
                createWith: 'tldraw_create_basic_shape',
                agentExposedArgs: {
                    kind: 'js-shape',
                    x: 'page x coordinate',
                    y: 'page y coordinate',
                    w: 'width, default 320',
                    h: 'height, default 220',
                    color: 'panel color',
                    text: 'stored only as a note in placeholder data',
                    select: 'select after create unless false',
                    zoom: 'zoom to result unless false',
                },
                nativePropsAndBehavior: [
                    'Native props include w,h,color,script,autoRun,interactive,restrictDom,data.',
                    'Runtime exposes dom, saveData(data), getData(), clearData(), and read-only shape snapshot. restrictDom defaults true.',
                    'User editing has a confirm window and can run scripts; Agent-supplied script execution is blocked.',
                ],
                operations: [
                    'Create a placeholder for the user to edit manually.',
                    'Move/resize/recolor with update tools.',
                    'Do not attempt to set script, data, autoRun, interactive, or restrictDom through Agent tools.',
                ],
            },
        ],
        basicShapeGuide: [
            'Default basic shapes are text, frame, and bezier-connector.',
            'Use text for short unlinked annotations; avoid note unless the user asks for sticky notes.',
            'Use frame for ordinary grouping and visual boundaries; avoid geo rectangles for grouping unless the user asks for geometric shapes.',
            'Use bezier-connector through tldraw_create_connector for ordinary relationships; use branch through tldraw_apply_plan for mind maps and hierarchy; avoid arrow/line unless the user asks for arrows, straight lines, or non-binding marks.',
            'Use draw/highlight/slide/mind-map/js-shape only on explicit user request or a clearly matching workflow; editable mind-map is not the default for agent-created mind maps.',
        ],
        layoutRecipes: [
            'For most edits: use tldraw_apply_plan with steps. It can create cards using blockId or contentMarkdown/title, single-blocks, text labels, frames, branch hierarchies, connect relationship lines, update labels, layout selections, focus results, and save in one call.',
            'For mind maps/tree/parent-child structures: use op "branch"; with two selected shapes use {op:"branch",root:"$selection[0]",child:"$selection[1]"}.',
            'For a document map: create a main card for the document, create single-block leaves or child cards, then create a branch with op "branch" or tldraw_insert_doc_outline_mindmap.',
            'For concept links: get shape details, then create a bezier connector with shapeIds and a short text label.',
            'For visual grouping: use frame by default. For presentation workflows only when requested: create slide frames, place content inside them, then use select/zoom or slide UI focus.',
            'For outlines: prefer tldraw_insert_doc_outline_mindmap or siyuan_create_summary_doc_whiteboard over hand-placing many nodes.',
        ],
        destructive: [
            'tldraw_delete_shapes',
            'tldraw_delete_whiteboard_file',
        ],
        safetyRules: [
            'Agent actions must be enabled in plugin settings.',
            'Most write actions require the whiteboard to be open, so the user can observe the change.',
            'Prefer tldraw_apply_plan before low-level create/update/connect/layout actions. It has a 50-write cap, supports dryRun, and blocks script/raw mutation/delete operations.',
            'For low-level tools, call tldraw_get_interaction_context first, then prefer the focused whiteboard and current selection unless the user requested another target. tldraw_apply_plan can usually omit whiteboardId and use the focused whiteboard directly.',
            'Use tldraw_create_shape for STtools business shapes; default to card and single-block. Use tldraw_create_basic_shape for text and frame by default. Other shape kinds should be used only when the user explicitly asks or the task clearly requires them.',
            'Batch shape operations are capped at 50 items.',
            'Shape deletion is dry-run by default and requires confirm:true to execute.',
            'Linked SiYuan block shapes are protected from deletion unless allowLinkedBlockShapes:true is explicitly passed.',
            'Whiteboard file deletion is dry-run by default, requires confirm:true, and refuses to run while the whiteboard is open.',
            'Snapshot reads return summaries, not full whiteboard JSON.',
            'Backup preview returns simplified counts/samples, not full backup contents.',
            'JS shape creation uses a restricted placeholder; agent-supplied script content is not accepted.',
        ],
        intentionallyBlocked: [
            'Restoring/importing a whiteboard backup through Agent is blocked because it overwrites current data.',
            'Arbitrary raw store/props mutation is blocked.',
            'Agent-supplied JavaScript execution is blocked.',
            'tldraw_apply_plan cannot set script, autoRun, data, props, rootNode, or other raw custom shape internals.',
            'Full snapshot JSON exfiltration is blocked; create a backup file instead.',
            'Direct SiYuan block content deletion/update through tldraw actions is blocked.',
            'External asset insertion is blocked until upload, size, and type validation are implemented.',
        ],
    };
}
