export function getTldrawAgentCapabilities() {
    return {
        version: 3,
        enabled: true,
        agentPrompt: [
            'For whiteboard shape work, call tldraw_shape_command. It can use the focused whiteboard and current selection automatically.',
            'For complex canvas understanding, call tldraw_get_visual_context after tldraw_get_interaction_context. It provides viewport bounds, visible shapes, offscreen clusters, and optional SVG export so you can reason about spatial layout before editing.',
            'When calling tldraw_shape_command through the frontend plugin wrapper, pass intent, target, patch, node, nodes, from, and to as direct named arguments even if the visible generic schema only lists action/id/query.',
            'Do not encode the whole tldraw_shape_command payload into id or query. id is only a whiteboardId fallback; omit it when the focused whiteboard is already open.',
            'To answer "what is the selected card content?", call tldraw_shape_command with {intent:"readSelectedContent"}; do not fetch shape ids first.',
            'To change selected custom shape properties, call tldraw_shape_command with intent "inspectEditable" if you need available fields, then intent "updateShape" with a small patch.',
            'To modify linked card content, first ask the user for explicit confirmation. Only after the user confirms, call tldraw_shape_command with intent "updateShape", contentMarkdown or patch.contentMarkdown, and confirmContentUpdate:true. Without confirmContentUpdate:true, the tool refuses the write. The tool writes the linked SiYuan block, keeps generated headings below the bound heading level, refreshes all cards for that block, and autosaves the board.',
            'When creating a card with blockId, omit isMain unless you need to override it. The tool treats document blocks as main cards and heading blocks as normal cards.',
            'To create shapes, call tldraw_shape_command with intent "createShapes" and pass node or nodes. Use layoutStyle instead of manual coordinates unless exact placement is requested.',
            'To connect shapes, call tldraw_shape_command with intent "connectShapes"; pass from/to or select two shapes first. Use connectionKind "branch" for hierarchy and "relation" for ordinary links.',
            'For branch hierarchy connections or side changes, do not pre-move child shapes or run a separate layout first. Branch auto-positions its children; only choose root/from, child/to, optional side, and optional spacing/style. The root shape or branch center controls the main position.',
            'To move a branch child from the left side to the right side, call connectShapes again with the same root/branch as from, the child as to, connectionKind "branch", and side "right"; this updates branch leftChildIds/rightChildIds and relayouts automatically.',
            'Branch constraints: root content can only be card or single-block; branch children can only be card, single-block, or branch; never branch-connect text/note/geo/frame/slide/mind-map/js-shape/arrow/connector shapes. Do not create branch cycles or a second root branch for the same root card.',
            'For complex branch edits, inspect/read shape details first. Branch summaries expose rootShapeId, leftChildIds, rightChildIds, and childIds; use those ids instead of guessing from visual x/y positions.',
            'To arrange or frame shapes, call tldraw_shape_command with intent "layoutShapes" and layoutStyle "nearSelection", "rightOf", "below", "grid", "tree", "mindmap", or "frameAround".',
            'To import Mermaid diagrams into the board, call tldraw_import_mermaid with mermaid text. Omit whiteboardId to use the focused whiteboard.',
            'If the user refers to the current board or selected shapes, omit whiteboardId and use $selection / $selection[0]. The focused whiteboard is used automatically.',
            'Use card for existing document/heading blocks or substantial content, single-block for compact notes, text/note for unlinked labels, frame for visual grouping, slide/mind-map/js-shape for their custom experiences.',
            'The old board-edit DSL tool is intentionally not registered. Do not construct operations arrays.',
            'To create a new whiteboard, call tldraw_open_whiteboard with createNew:true or omit whiteboardId and pass a title. The tool creates the backing SiYuan document and opens its whiteboard; do not invent a whiteboardId.',
            'The open whiteboard autosaves every edit, so do not pass save:true on each operation and do not call tldraw_save_whiteboard after every change. Omit save and let autosave persist the edit. Call tldraw_save_whiteboard only when the user explicitly asks to flush immediately (for example, right before closing).',
            'You may execute ordinary shape deletion autonomously: call tldraw_delete_shapes with confirm:true and go straight to execution. A whiteboard backup is always created before any confirmed deletion, so the backup-before-delete rule is satisfied automatically; never try to bypass it. Linked SiYuan block shapes are different: do not delete them unless the user explicitly asked to delete linked block shapes; only then pass allowLinkedBlockShapes:true and confirmLinkedBlockShapes:true. Omit confirm only when you want a dry-run preview of what would be deleted.',
        ],
        preferred: [
            'tldraw_shape_command',
        ],
        read: [
            'tldraw_shape_command',
            'tldraw_get_interaction_context',
            'tldraw_get_visual_context',
            'tldraw_list_whiteboards',
            'tldraw_get_summary',
            'tldraw_get_shape_details',
            'tldraw_get_snapshot_summary',
            'tldraw_list_backups',
            'tldraw_preview_backup',
            'siyuan_read_doc_outline_for_tldraw',
        ],
        openNavigateSave: [
            'tldraw_open_whiteboard',
            'tldraw_import_mermaid',
            'tldraw_select_shape',
            'tldraw_zoom_to_shapes',
            'tldraw_navigate_to_block',
            'tldraw_save_whiteboard',
        ],
        createEditLayout: [
            'tldraw_shape_command',
            'tldraw_import_mermaid',
        ],
        toolSelectionHints: {
            shapeCommand: {
                action: 'tldraw_shape_command',
                purpose: 'Primary semantic tool for custom-shape reads, creation, connection, layout, focusing, editable-field inspection, and property updates.',
                references: ['$selection', '$selection[0]', '$block.<blockId>', '$kind.card', '$kind.single-block', '$kind.branch', '$kind.bezier-connector', '$kind.mind-map', '$kind.slide', '$kind.js-shape'],
                intents: ['readSelectedContent', 'inspectEditable', 'updateShape', 'createShapes', 'connectShapes', 'layoutShapes', 'focusShapes'],
                editableExamples: {
                    card: ['color', 'isCollapsed', 'showMask', 'isMain', 'renderMode', 'collapsedTextSize', 'collapsedTextAlign', 'contentMarkdown'],
                    'single-block': ['color', 'transparentBackground', 'allowBinding', 'connectOnEnter'],
                    branch: ['color', 'lineStyle', 'lineWidth', 'horizontalGap', 'verticalGap', 'snapDistance', 'showBackground'],
                    'bezier-connector': ['color', 'strokeWidth', 'strokeStyle', 'labelPosition', 'text'],
                    'mind-map': ['color', 'theme', 'direction', 'fontSize', 'nodeWidth', 'nodeHeight', 'lineWidth', 'horizontalGap', 'verticalGap', 'text'],
                    slide: ['color', 'name', 'borderStyle'],
                    'js-shape': ['color', 'interactive', 'restrictDom'],
                },
                defaults: {
                    whiteboardId: 'omit it for the focused board',
                    target: '$selection',
                    save: 'omit it 鈥?the open whiteboard autosaves every edit; only tldraw_save_whiteboard forces an immediate flush',
                    callShape: 'pass intent/target/patch as direct named args; do not pack them into id/query',
                },
                examples: [
                    { intent: 'readSelectedContent' },
                    { intent: 'inspectEditable', target: '$selection[0]' },
                    { intent: 'updateShape', target: '$selection[0]', patch: { color: 'blue', isCollapsed: true } },
                    { intent: 'updateShape', target: '$selection[0]', contentMarkdown: '## Updated card title\n\nNew card body', confirmContentUpdate: true },
                    { intent: 'createShapes', nodes: [{ kind: 'single-block', text: 'New note' }], layoutStyle: 'nearSelection' },
                    { intent: 'connectShapes', from: '$selection[0]', to: '$selection[1]', connectionKind: 'relation', text: 'related' },
                    { intent: 'connectShapes', from: '$selection[0]', to: '$selection[1]', connectionKind: 'branch', side: 'right' },
                    { intent: 'connectShapes', from: '$kind.branch', to: '$selection[0]', connectionKind: 'branch', side: 'right' },
                    { intent: 'layoutShapes', target: '$selection', layoutStyle: 'grid', columns: 3 },
                ],
            },
            mermaidImport: {
                action: 'tldraw_import_mermaid',
                guidance: 'Use this when the user provides Mermaid syntax and wants a diagram placed on the whiteboard as editable shapes instead of plain text.',
            },
            inspect: {
                action: 'tldraw_shape_command',
                guidance: 'Use tldraw_shape_command inspectEditable/readSelectedContent for selected custom-shape work. Use tldraw_get_shape_details only when exact bounds, bindings, or many raw shape details are needed.',
            },
            visualContext: {
                action: 'tldraw_get_visual_context',
                guidance: 'Use this before non-trivial layouts or edits that depend on viewport composition. It combines structured shape summaries with viewport and offscreen cluster context, similar to the tldraw agent starter kit visual context system.',
            },
        },
        customShapeGuide: [
            {
                type: 'card',
                purpose: 'A large SiYuan document or heading card for article sections, overview documents, or rich linked content.',
                createWith: 'tldraw_shape_command intent createShapes with node kind "card".',
                notes: [
                    'Use blockId to reference an existing document/heading block, or contentMarkdown/title/text to create a new heading block.',
                    'Content belongs to the bound SiYuan block; after explicit user confirmation, use tldraw_shape_command updateShape with contentMarkdown and confirmContentUpdate:true to replace card content. The tool refreshes the card and fixes generated heading levels automatically.',
                    'When blockId points to a document block the card defaults to isMain:true; when it points to a heading block the card defaults to isMain:false. Explicit isMain overrides this.',
                ],
            },
            {
                type: 'single-block',
                purpose: 'A compact SiYuan paragraph block for atomic notes, branch leaves, labels, todos, and short facts.',
                createWith: 'tldraw_shape_command intent createShapes with node kind "single-block".',
                notes: [
                    'Use blockId for an existing paragraph, or text/contentMarkdown/title to create a new paragraph block.',
                    'Use this as the default branch leaf and compact content node.',
                    'Use tldraw_shape_command for simple reads and property updates of selected single-block shapes.',
                ],
            },
            {
                type: 'branch',
                purpose: 'A visual hierarchy connector from one root shape to left/right child shapes.',
                createWith: 'tldraw_shape_command intent connectShapes with connectionKind "branch".',
                notes: [
                    'Do not hand-place branch geometry and do not update child x/y before connecting or changing sides. Provide from/to refs and optional side/style/spacing; branch will move children into place automatically.',
                    'The branch position is driven by the root shape center, or by the branch center when connecting from an existing branch.',
                    'Changing a child from left to right means updating branch membership, not moving the child shape: call connectShapes with the same root/branch, the child, and side "right".',
                    'Root content is limited to card/single-block. Children are limited to card/single-block/branch. If a card/single-block is already the root of another branch, connect that branch container instead of the raw root shape.',
                    'Never connect a branch to itself, to an ancestor/descendant that would create a cycle, or to a branch that already contains the target root shape.',
                    'A card/single-block should have only one root branch; reuse the existing branch/root connection instead of creating another branch shape.',
                    'Use side "right" or "left" for explicit one-sided branches; omit side when the current child position should decide the side.',
                    'Use tldraw_shape_command to update branch lineStyle, lineWidth, spacing, snapDistance, color, and showBackground.',
                ],
            },
            {
                type: 'bezier-connector',
                purpose: 'A curved, bindable relationship connector with an optional label.',
                createWith: 'tldraw_shape_command intent connectShapes with connectionKind "relation".',
                notes: [
                    'Use relation connections for non-hierarchical semantic links.',
                    'The runtime chooses shape ports automatically.',
                    'Use tldraw_shape_command to update strokeWidth, strokeStyle, labelPosition, label text, and color.',
                ],
            },
            {
                type: 'frame',
                purpose: 'A visual boundary around related shapes.',
                createWith: 'tldraw_shape_command intent createShapes with node kind "frame", or layoutShapes with layoutStyle "frameAround".',
                notes: [
                    'Use frameAround when grouping existing shapes visually.',
                ],
            },
            {
                type: 'mind-map',
                purpose: 'A custom structured mind-map shape with editable root text, theme, direction, node sizing, and spacing.',
                createWith: 'tldraw_shape_command intent createShapes with node kind "mind-map".',
                notes: [
                    'Use tldraw_shape_command for root text, theme, direction, fontSize, nodeWidth, nodeHeight, lineWidth, spacing, size, and color.',
                    'Node-level add/move/delete remains outside tldraw_shape_command in this version.',
                ],
            },
            {
                type: 'slide',
                purpose: 'A custom slide frame used for focused whiteboard presentation sections.',
                createWith: 'tldraw_shape_command intent createShapes with node kind "slide".',
                notes: [
                    'Use tldraw_shape_command to update slide name, borderStyle, size, position, and color.',
                    'Screenshot capture and block linking remain UI-specific actions.',
                ],
            },
            {
                type: 'js-shape',
                purpose: 'A custom JavaScript-rendered shape.',
                createWith: 'tldraw_shape_command intent createShapes with node kind "js-shape".',
                notes: [
                    'Use tldraw_shape_command to update size, position, color, interactive, and restrictDom.',
                    'Agent-supplied script and raw data writes remain blocked.',
                ],
            },
        ],
        layoutRecipes: [
            'Inspect selected shapes: tldraw_shape_command intent inspectEditable.',
            'Read selected linked content: tldraw_shape_command intent readSelectedContent.',
            'Update selected shape fields: tldraw_shape_command intent updateShape with a small patch.',
            'Create notes/shapes: tldraw_shape_command intent createShapes with node/nodes and layoutStyle.',
            'Connect or change branch side: tldraw_shape_command intent connectShapes with connectionKind "branch"; pass side "left" or "right"; do not pre-layout or move children, branch auto-arranges them from the root/branch center.',
            'Connect ordinary relations: tldraw_shape_command intent connectShapes with connectionKind "relation".',
            'Arrange or frame shapes: tldraw_shape_command intent layoutShapes with target and layoutStyle.',
            'Select and zoom: tldraw_shape_command intent focusShapes.',
        ],
        hiddenLegacyActions: [
            'The old board-edit DSL and legacy/basic write actions are intentionally not registered for Agent use.',
        ],
        destructive: [
            'tldraw_delete_shapes',
            'tldraw_delete_whiteboard_file',
        ],
        safetyRules: [
            'Agent actions must be enabled in plugin settings.',
            'Most write actions require the whiteboard to be open so the user can observe changes.',
            'tldraw_shape_command only changes whitelisted semantic fields and never performs raw props mutation, JS script writes, or arbitrary data writes.',
            'Default results do not include raw snapshots, full props, or shape samples.',
            'tldraw_get_visual_context returns a bounded scene summary and optional SVG preview rather than raw canvas snapshots.',
            'Shape deletion uses tldraw_delete_shapes (not tldraw_shape_command). The agent may execute ordinary shape deletion autonomously with confirm:true; a backup is always created before confirmed deletion. Linked SiYuan block shapes require explicit user intent and are blocked unless allowLinkedBlockShapes:true and confirmLinkedBlockShapes:true are both passed.',
            'JS shape script execution, arbitrary raw store mutation, backup restore/import, and direct SiYuan block content edits remain blocked.',
        ],
        intentionallyBlocked: [
            'Restoring/importing a whiteboard backup through Agent is blocked because it overwrites current data.',
            'Arbitrary raw store/props mutation is blocked.',
            'Agent-supplied JavaScript execution is blocked.',
            'Full snapshot JSON exfiltration is blocked; create a backup file instead.',
            'Direct SiYuan block content deletion/update through tldraw actions is blocked.',
            'External asset insertion is blocked until upload, size, and type validation are implemented.',
        ],
    };
}
