export function getTldrawAgentCapabilities() {
    return {
        version: 1,
        enabled: true,
        read: [
            'tldraw_get_interaction_context',
            'tldraw_list_whiteboards',
            'tldraw_get_summary',
            'tldraw_get_shape_details',
            'tldraw_get_snapshot_summary',
            'tldraw_list_backups',
            'tldraw_preview_backup',
            'siyuan_read_doc_outline_for_tldraw',
        ],
        openNavigateSave: [
            'tldraw_open_whiteboard',
            'tldraw_select_shape',
            'tldraw_zoom_to_shapes',
            'tldraw_navigate_to_block',
            'tldraw_save_whiteboard',
        ],
        createEditLayout: [
            'tldraw_create_shape',
            'tldraw_create_basic_shape',
            'tldraw_create_connector',
            'tldraw_update_shape',
            'tldraw_batch_update_shapes',
            'tldraw_duplicate_shapes',
            'tldraw_arrange_shapes',
            'tldraw_align_shapes',
            'tldraw_group_shapes',
            'tldraw_lock_shapes',
            'tldraw_convert_connectors',
            'tldraw_insert_doc_outline_mindmap',
            'siyuan_create_summary_child_doc_whiteboard',
        ],
        toolSelectionHints: {
            createBusinessShapes: {
                action: 'tldraw_create_shape',
                kinds: ['card', 'single-block', 'branch'],
                exampleArgs: { whiteboardId: '<focusedWhiteboardId>', kind: 'card', x: 100, y: 100, zoom: false },
            },
            createBasicShapes: {
                action: 'tldraw_create_basic_shape',
                kinds: ['note', 'text', 'geo', 'arrow', 'line', 'draw', 'highlight', 'frame', 'bezier-connector', 'slide', 'mind-map', 'js-shape'],
                exampleArgs: { whiteboardId: '<focusedWhiteboardId>', kind: 'note', x: 100, y: 100, text: 'test', zoom: false },
            },
            createConnectorsBetweenShapes: {
                action: 'tldraw_create_connector',
                exampleArgs: { whiteboardId: '<focusedWhiteboardId>', shapeIds: ['shape:<source>', 'shape:<target>'], text: 'label', zoom: false },
            },
        },
        destructive: [
            'tldraw_delete_shapes',
            'tldraw_delete_whiteboard_file',
        ],
        safetyRules: [
            'Agent actions must be enabled in plugin settings.',
            'Most write actions require the whiteboard to be open, so the user can observe the change.',
            'Agents should call tldraw_get_interaction_context before using whiteboard tools, then prefer the focused whiteboard and current selection unless the user requested another target.',
            'Use tldraw_create_shape for STtools business shapes (card, single-block, branch); use tldraw_create_basic_shape for note, text, geo, arrow, line, frame, and similar basic shapes.',
            'Batch shape operations are capped at 50 items.',
            'Shape deletion is dry-run by default and requires confirm:true to execute.',
            'Linked SiYuan block shapes are protected from deletion unless allowLinkedBlockShapes:true is explicitly passed.',
            'Whiteboard file deletion is dry-run by default, requires confirm:true, and refuses to run while the whiteboard is open.',
            'Snapshot reads return summaries, not full whiteboard JSON.',
            'Backup preview returns simplified counts/samples, not full backup contents.',
            'JS shape creation uses a restricted placeholder; agent-supplied script content is not accepted.',
        ],
        intentionallyBlocked: [
            'Restoring/importing a whiteboard backup through Agent is blocked because it overwrites current data.',
            'Arbitrary raw store/props mutation is blocked.',
            'Agent-supplied JavaScript execution is blocked.',
            'Full snapshot JSON exfiltration is blocked; create a backup file instead.',
            'Direct SiYuan block content deletion/update through tldraw actions is blocked.',
            'External asset insertion is blocked until upload, size, and type validation are implemented.',
        ],
    };
}
